### ISSUE TITLE
Returning empty string when reading list from config

### ISSUE THREAD

**Issue by egemenzeytinci** [trK54Ylmz/ini-klass#9]
Here is an example,

ini file,
```ini
[example]
id = 12
name = John
status = true
salary = 100.50
group = car,
```

code,
```python
from ini import IniConfig

# read from file
config = IniConfig.read('/tmp/file.ini')

# access configuration value
group = config.example.group

print(group)
```

It returns list like `['car', '']` and it causes an error when I try to create a session for Cassandra. As you know, several connectors need a list for hosts such as Elasticsearch, Cassandra, etc. It's okay for Elastic, but for Cassandra, when I give a list like `['x.x.x.x', '']` it connects to localhost. Do you have any idea to fix this?

Thanks in advance.

**Comment by trK54Ylmz** [comment]
Fixed with the new version which is `0.0.4`
